### PR TITLE
chore(package): update eslint to version 5.0.1

### PR DESCRIPTION
**Pull request by whity**
Closes #57

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Ignore the beta failure on CircleCI, it's due to https://github.com/atom/apm/issues/746.

**Comment by whity** [comment]
Thanks for the tip @Arcanemagus

**Comment by Arcanemagus** [comment]
And as an FYI, that failure is fixed on v1.31.0-beta1, so beta failures are valid again ;)

I also restarted all the builds, so status should be green where applicable again.

**Pull request merged**
