### PR TITLE
Fix deployment stage of the Travis CI builds

### PR DESCRIPTION
**Pull request by Arcanemagus**
This PR fixes the deployment stage of the Travis CI builds so it can actually run.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Let's see if this works...

**Comment by Arcanemagus** [comment]
This was a tricky one, got it working with https://github.com/AtomLinter/atom-linter-perlcritic/commit/7d1b63063fe85c6077f5487ec788abcd4d561388 though!

**Comment by whity** [comment]
Nice work 😄

**Pull request merged**
